### ISSUE TITLE
Collaboration

### ISSUE THREAD

**Issue by orchid00** [SoftDev4Research/4OSS-lesson#19]
Make clear what your project is and how to contribute, for new and existing collaborators 

From [Good enough practices for scientific computing](http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005510)
-  Create an overview of your project. (MUST INCLUDE)
-  Create a shared "to-do" list for the project. (MUST INCLUDE)
-  Decide on communication strategies. (MUST INCLUDE)
-  Make the license explicit. (will be part of the license recomendation)
-  Make the project citable (where to add?)

Except for the To-do list all of the above should be on the README file. I'm working on [this](https://github.com/SoftDev4Research/4OSS-lesson/blob/gh-pages/README.md)

**Comment by orchid00** [comment]
Improving [CONTRIBUTING.md](https://github.com/SoftDev4Research/4OSS-lesson/blob/gh-pages/CONTRIBUTING.md)

- [x]  location root-project/CONTRIBUTING.md
- [x]  cheer: Give  super nice welcome to contributors!
- [x]  introduction: Overview of the document 
- [x]  how-to: cover the basics of expected contributions and times
- [ ]  style: Add a style guide

Examples
- https://github.com/atom/atom/blob/master/CONTRIBUTING.md
- http://r4ds.had.co.nz/contribute.html
- https://github.com/galaxyproject/galaxy/blob/dev/CONTRIBUTING.md
- https://github.com/ropensci/plotly/blob/master/CONTRIBUTING.md
- https://github.com/ropensci/scrubr/blob/master/CONTRIBUTING.md
- https://github.com/ropensci/dev_guide/blob/7672a91d2da72fa5ac00083de5391a3c45f8dc5e/maintenance_contributing.Rmd
- https://discourse.ubuntu.com/t/contribute/26 and https://wiki.ubuntu.com/ContributeToUbuntu
- ropensci https://github.com/search?l=Markdown&q=org%3Aropensci+CONTRIBUTING.md&type=Code

Other links
- https://ropensci.shinyapps.io/contributr/
- https://github.com/ropensci/dev_guide/blob/7672a91d2da72fa5ac00083de5391a3c45f8dc5e/maintenance_collaboration.Rmd
- https://ropensci.github.io/dev_guide/contributingguide.html
- Mozilla ScienceLabs [CONTRIBUTING.md quick presentation](https://docs.google.com/presentation/d/1YZA8rvD2Ix4F7y4ck44XYwTlQZ_YkM4higpuwy5swy8/edit#slide=id.gef398db8c_0_0)

**Comment by fmichonneau** [comment]
Other examples:
- pandas: https://pandas.pydata.org/pandas-docs/stable/contributing.html
- dplyr: https://github.com/tidyverse/dplyr/blob/master/.github/CONTRIBUTING.md
- octobox: https://github.com/octobox/octobox#contribute
- scipy: https://github.com/scipy/scipy/blob/master/CONTRIBUTING.rst
- sf package: https://github.com/r-spatial/sf#contributing
- knitr: https://github.com/yihui/knitr/blob/master/.github/CONTRIBUTING.md
- rmarkdown: https://github.com/rstudio/rmarkdown/blob/master/CONTRIBUTING.md

**Comment by orchid00** [comment]
I will close this issue.
Everyone who has a suggested resource please make a PR
