### ISSUE TITLE
Content of introduction

### ISSUE THREAD

**Issue by tobyhodges** [SoftDev4Research/4OSS-lesson#44]
We didn't discuss what will go into the introductory episode. A couple of thoughts:

1. The licensing episode relies on learners having already created a project on GitHub, which means that we need to move that section out of episode 3, either into the introduction or as a prerequisite (we can put the instructions into `extras` or get rid of it entirely and link to another online guide)
2. The introduction seems like a good place to answer the question "why open source?" I would like to see this acknowledge and address some of the "fears" listed in the supplementary materials of the paper ([link](https://f1000research.com/articles/6-876/v1#SM1)), perhaps as an exercise/icebreaker.

**Comment by fpsom** [comment]
I think that I've somewhat addressed both points in PR #52 . Comments and suggestions are obviously more than welcome. 

We can close the issue when the PR is merged.

**Comment by tobyhodges** [comment]
I think that we still need to move the "Create a project on GitHub" exercise/guide out of make-it-public before we can close this. The question is: do we put it in extras or in the introduction?

**Comment by tobyhodges** [comment]
In #50, I move it into the introduction. If that gets merged in addition to #52, then I agree that we can close this.

**Comment by fpsom** [comment]
That is a fair point; I agree that it seems better fitted to the introduction so I can merge #50 (I see that it's ready to be merged in any case), and then try to fix the introduction so that the "Create a project" part is at the end of the episode itself. Sounds good?

**Comment by tobyhodges** [comment]
Sounds good to me :+1:

**Comment by fpsom** [comment]
Ok, done. If there are no other suggestions/edits, I will be closing this issue.

**Comment by tobyhodges** [comment]
:+1: thanks, Fotis :)
