### ISSUE TITLE
Order of Episodes

### ISSUE THREAD

**Issue by fpsom** [SoftDev4Research/4OSS-lesson#7]
Order of episodes/recommendations should be the following:
1. 3rd recommendation "_Adopt a licence and comply with the licence of third-party dependencies_"
2. 1st recommendation "_Make source code publicly accessible from day one_"
3. 4th recommendation "_Define clear and transparent contribution, governance and communication processes_"
4. 2nd recommendation "_Make software easy to discover by providing software metadata via a popular community registry_"

**Comment by orchid00** [comment]
We should change the labels, maybe a short name instead of a number
@mkuzak

**Comment by mkuzak** [comment]
What should be the new labels? License, source, contribution, metadata?

**Comment by allegravia** [comment]
Sound reasonable labels… :-)

**Comment by fpsom** [comment]
I agree. It would be much more useful for imparting information at first glance.

**Comment by mkuzak** [comment]
and more stable in case we change the order again :)

**Comment by orchid00** [comment]
Thanks for the comments, I've changed the label names https://github.com/SoftDev4Research/4OSS-lesson/labels

**Comment by fpsom** [comment]
I'm closing this issue, as:
- the labels have been created
- the order of the episodes has been decided during the hackathon and different than the plan proposed on June 1st.

**Comment by orchid00** [comment]
@orchid00 I'll change the order

**Comment by orchid00** [comment]
Order of episodes/recommendations should be the following:

    1st recommendation "Make source code publicly accessible from day one"
    3rd recommendation "Adopt a licence and comply with the licence of third-party dependencies"
    4th recommendation "Define clear and transparent contribution, governance and communication processes"
    2nd recommendation "Make software easy to discover by providing software metadata via a popular community registry"

**Comment by orchid00** [comment]
Done! :tada: :tada: :tada: 
episodes order sorted @fpsom @mkuzak @allegravia @rajido
https://github.com/SoftDev4Research/4OSS-lesson/tree/gh-pages/_episodes
https://softdev4research.github.io/4OSS-lesson/

**Comment by fpsom** [comment]
Thanks @orchid00 !
