### ISSUE TITLE
Add definition of notebook

### ISSUE THREAD

**Issue by deniseOme** [SoftDev4Research/4OSS-lesson#83]
In 4OSS-lesson/_episodes/02-make-it-public.md, we have the "What if your software is an analysis in a Notebook" but there is no definition of the term "notebooks", rather we start writing about Jupyter straightway.

It'll be useful to include a general definition of "notebooks". @mkuzak is currently writing one.

**Comment by orchid00** [comment]
Great! I'm looking forward to see this PR

**Comment by orchid00** [comment]
fixed by https://github.com/SoftDev4Research/4OSS-lesson/pull/87 
closing
